const { AsyncLocalStorage } = require("async_hooks");

const transactionStorage = new AsyncLocalStorage();

function isLikelySqlitePragma(sql) {
  return /^\s*PRAGMA\s+foreign_keys\s*=\s*ON\s*;?\s*$/i.test(String(sql || ""));
}

function parseTableInfoPragma(sql) {
  const match = /^\s*PRAGMA\s+table_info\s*\(\s*([^)]+?)\s*\)\s*;?\s*$/i.exec(String(sql || ""));
  if (!match) {
    return null;
  }
  const tableName = String(match[1] || "").trim().replace(/^["']|["']$/g, "");
  return tableName || null;
}

function parseSqliteTableExistsQuery(sql) {
  const normalized = String(sql || "").replace(/\s+/g, " ").trim();
  const match = /^SELECT name FROM sqlite_master WHERE type = 'table' AND name = '([^']+)'$/i.exec(normalized);
  return match ? match[1] : null;
}

function replaceQuestionPlaceholders(sql) {
  let output = "";
  let placeholderIndex = 1;
  let inSingleQuote = false;
  let inDoubleQuote = false;
  let inBacktick = false;
  let inLineComment = false;
  let inBlockComment = false;

  for (let i = 0; i < sql.length; i += 1) {
    const char = sql[i];
    const next = sql[i + 1];

    if (inLineComment) {
      output += char;
      if (char === "\n") {
        inLineComment = false;
      }
      continue;
    }

    if (inBlockComment) {
      output += char;
      if (char === "*" && next === "/") {
        output += next;
        i += 1;
        inBlockComment = false;
      }
      continue;
    }

    if (!inSingleQuote && !inDoubleQuote && !inBacktick) {
      if (char === "-" && next === "-") {
        output += char + next;
        i += 1;
        inLineComment = true;
        continue;
      }
      if (char === "/" && next === "*") {
        output += char + next;
        i += 1;
        inBlockComment = true;
        continue;
      }
    }

    if (!inDoubleQuote && !inBacktick && char === "'" && !inLineComment && !inBlockComment) {
      output += char;
      if (inSingleQuote && next === "'") {
        output += next;
        i += 1;
      } else {
        inSingleQuote = !inSingleQuote;
      }
      continue;
    }

    if (!inSingleQuote && !inBacktick && char === '"' && !inLineComment && !inBlockComment) {
      output += char;
      inDoubleQuote = !inDoubleQuote;
      continue;
    }

    if (!inSingleQuote && !inDoubleQuote && char === "`" && !inLineComment && !inBlockComment) {
      output += char;
      inBacktick = !inBacktick;
      continue;
    }

    if (char === "?" && !inSingleQuote && !inDoubleQuote && !inBacktick) {
      output += `$${placeholderIndex}`;
      placeholderIndex += 1;
      continue;
    }

    output += char;
  }

  return output;
}

function rewriteSqliteSyntax(sql) {
  return String(sql || "");
}

function rewritePostgresSyntax(sql) {
  let rewritten = String(sql || "");
  rewritten = rewritten.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
  rewritten = rewritten.replace(/\bBEGIN\s+IMMEDIATE\s+TRANSACTION\b/gi, "BEGIN");
  rewritten = rewritten.replace(/\bBEGIN\s+EXCLUSIVE\s+TRANSACTION\b/gi, "BEGIN");
  rewritten = rewritten.replace(/\bDATE\(\s*'now'\s*\)/gi, "CURRENT_DATE");
  return rewritten;
}

function normalizeResultRow(row) {
  if (!row || typeof row !== "object") {
    return row;
  }
  const next = {};
  for (const [key, value] of Object.entries(row)) {
    next[key] = value instanceof Date ? value.toISOString() : value;
  }
  return next;
}

function normalizeResultRows(rows) {
  return Array.isArray(rows) ? rows.map((row) => normalizeResultRow(row)) : [];
}

function buildPgTableInfoQuery(tableName) {
  return {
    text: `
      SELECT
        c.ordinal_position - 1 AS cid,
        c.column_name AS name,
        c.data_type AS type,
        CASE WHEN c.is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
        c.column_default AS dflt_value,
        CASE
          WHEN EXISTS (
            SELECT 1
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.table_schema = current_schema()
              AND tc.table_name = $1
              AND tc.constraint_type = 'PRIMARY KEY'
              AND kcu.column_name = c.column_name
          ) THEN 1
          ELSE 0
        END AS pk
      FROM information_schema.columns c
      WHERE c.table_schema = current_schema()
        AND c.table_name = $1
      ORDER BY c.ordinal_position
    `,
    values: [tableName],
  };
}

function buildPgTableExistsQuery(tableName) {
  return {
    text: "SELECT $1::text AS name WHERE to_regclass($1) IS NOT NULL",
    values: [tableName],
  };
}

function createSqliteClient(dbPath) {
  let sqlite3;
  try {
    sqlite3 = require("sqlite3").verbose();
  } catch (err) {
    if (err && err.code === "MODULE_NOT_FOUND") {
      throw new Error('Missing dependency "sqlite3". Install it with: npm install sqlite3');
    }
    throw err;
  }

  const db = new sqlite3.Database(dbPath);
  db.run("PRAGMA foreign_keys = ON");

  function run(sql, params = []) {
    return new Promise((resolve, reject) => {
      const pragmaTable = parseTableInfoPragma(sql);
      const existsTable = parseSqliteTableExistsQuery(sql);
      if (isLikelySqlitePragma(sql) || pragmaTable || existsTable) {
        resolve({ lastID: 0, changes: 0, rowCount: 0, rows: [] });
        return;
      }

      const rewrittenSql = rewriteSqliteSyntax(sql);
      db.run(rewrittenSql, params, function onRun(err) {
        if (err) {
          reject(err);
          return;
        }
        resolve({
          lastID: Number(this.lastID || 0),
          changes: Number(this.changes || 0),
          rowCount: Number(this.changes || 0),
          rows: [],
        });
      });
    });
  }

  function get(sql, params = []) {
    return new Promise((resolve, reject) => {
      const pragmaTable = parseTableInfoPragma(sql);
      const existsTable = parseSqliteTableExistsQuery(sql);
      if (pragmaTable) {
        db.all(`PRAGMA table_info(${pragmaTable})`, (err, rows) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(rows && rows.length ? rows[0] : null);
        });
        return;
      }
      if (existsTable) {
        db.get(
          "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?",
          [existsTable],
          (err, row) => {
            if (err) {
              reject(err);
              return;
            }
            resolve(row || null);
          }
        );
        return;
      }

    const rewrittenSql = rewriteSqliteSyntax(sql);
      db.get(rewrittenSql, params, (err, row) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(row || null);
      });
    });
  }

  function all(sql, params = []) {
    return new Promise((resolve, reject) => {
      const pragmaTable = parseTableInfoPragma(sql);
      const existsTable = parseSqliteTableExistsQuery(sql);
      if (pragmaTable) {
        db.all(`PRAGMA table_info(${pragmaTable})`, (err, rows) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(rows || []);
        });
        return;
      }
      if (existsTable) {
        db.get(
          "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?",
          [existsTable],
          (err, row) => {
            if (err) {
              reject(err);
              return;
            }
            resolve(row ? [row] : []);
          }
        );
        return;
      }

      const rewrittenSql = rewriteSqliteSyntax(sql);
      db.all(rewrittenSql, params, (err, rows) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(rows || []);
      });
    });
  }

  async function transaction(work) {
    await run("BEGIN IMMEDIATE TRANSACTION");
    try {
      const result = await work();
      await run("COMMIT");
      return result;
    } catch (err) {
      try {
        await run("ROLLBACK");
      } catch (_rollbackErr) {
        // ignore rollback failures
      }
      throw err;
    }
  }

  function close(callback) {
    return new Promise((resolve, reject) => {
      db.close((err) => {
        if (typeof callback === "function") {
          callback(err || undefined);
        }
        if (err) {
          reject(err);
          return;
        }
        resolve();
      });
    });
  }

  return {
    kind: "sqlite",
    db,
    run,
    get,
    all,
    transaction,
    close,
  };
}

function createPgClient(databaseUrl) {
  let Pool;
  try {
    ({ Pool } = require("pg"));
  } catch (err) {
    if (err && err.code === "MODULE_NOT_FOUND") {
      throw new Error('Missing dependency "pg". Install it with: npm install pg');
    }
    throw err;
  }

  const pool = new Pool({
    connectionString: databaseUrl,
  });

  function getCurrentClient() {
    return transactionStorage.getStore()?.client || null;
  }

  async function query(sql, params = []) {
    const currentClient = getCurrentClient();
    if (currentClient) {
      return currentClient.query(sql, params);
    }
    return pool.query(sql, params);
  }

  async function run(sql, params = []) {
    const pragmaTable = parseTableInfoPragma(sql);
    if (isLikelySqlitePragma(sql)) {
      return { lastID: 0, changes: 0, rowCount: 0, rows: [] };
    }
    if (pragmaTable) {
      const result = await query(buildPgTableInfoQuery(pragmaTable).text, buildPgTableInfoQuery(pragmaTable).values);
      return {
        lastID: 0,
        changes: Number(result.rowCount || 0),
        rowCount: Number(result.rowCount || 0),
        rows: normalizeResultRows(result.rows),
      };
    }

    const existsTable = parseSqliteTableExistsQuery(sql);
    if (existsTable) {
      const result = await query(buildPgTableExistsQuery(existsTable).text, buildPgTableExistsQuery(existsTable).values);
      return {
        lastID: 0,
        changes: Number(result.rowCount || 0),
        rowCount: Number(result.rowCount || 0),
        rows: normalizeResultRows(result.rows),
      };
    }

    let rewrittenSql = rewritePostgresSyntax(sql);
    rewrittenSql = replaceQuestionPlaceholders(rewrittenSql);
    const trimmedSql = rewrittenSql.trim().replace(/;$/, "");
    const needsReturning = /^\s*insert\b/i.test(trimmedSql) && !/\breturning\b/i.test(trimmedSql);
    const finalSql = needsReturning ? `${trimmedSql} RETURNING *` : trimmedSql;
    const result = await query(finalSql, params);
    const rows = normalizeResultRows(result.rows);
    const lastRow = rows.length ? rows[rows.length - 1] : null;
    return {
      lastID: Number(lastRow?.id || 0),
      changes: Number(result.rowCount || 0),
      rowCount: Number(result.rowCount || 0),
      rows,
    };
  }

  async function get(sql, params = []) {
    const pragmaTable = parseTableInfoPragma(sql);
    if (isLikelySqlitePragma(sql)) {
      return null;
    }
    if (pragmaTable) {
      const result = await query(buildPgTableInfoQuery(pragmaTable).text, buildPgTableInfoQuery(pragmaTable).values);
      return result.rows.length ? normalizeResultRow(result.rows[0]) : null;
    }

    const existsTable = parseSqliteTableExistsQuery(sql);
    if (existsTable) {
      const result = await query(buildPgTableExistsQuery(existsTable).text, buildPgTableExistsQuery(existsTable).values);
      return result.rows.length ? normalizeResultRow(result.rows[0]) : null;
    }

    let rewrittenSql = rewritePostgresSyntax(sql);
    rewrittenSql = replaceQuestionPlaceholders(rewrittenSql);
    const result = await query(rewrittenSql, params);
    return result.rows.length ? normalizeResultRow(result.rows[0]) : null;
  }

  async function all(sql, params = []) {
    const pragmaTable = parseTableInfoPragma(sql);
    if (isLikelySqlitePragma(sql)) {
      return [];
    }
    if (pragmaTable) {
      const result = await query(buildPgTableInfoQuery(pragmaTable).text, buildPgTableInfoQuery(pragmaTable).values);
      return normalizeResultRows(result.rows);
    }

    const existsTable = parseSqliteTableExistsQuery(sql);
    if (existsTable) {
      const result = await query(buildPgTableExistsQuery(existsTable).text, buildPgTableExistsQuery(existsTable).values);
      return normalizeResultRows(result.rows);
    }

    let rewrittenSql = rewritePostgresSyntax(sql);
    rewrittenSql = replaceQuestionPlaceholders(rewrittenSql);
    const result = await query(rewrittenSql, params);
    return normalizeResultRows(result.rows);
  }

  async function transaction(work) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      const result = await transactionStorage.run({ client }, async () => work());
      await client.query("COMMIT");
      return result;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch (_rollbackErr) {
        // ignore rollback failures
      }
      throw err;
    } finally {
      client.release();
    }
  }

  function close(callback) {
    return Promise.resolve(pool.end())
      .then(() => {
        if (typeof callback === "function") {
          callback();
        }
      })
      .catch((err) => {
        if (typeof callback === "function") {
          callback(err);
        }
        throw err;
      });
  }

  return {
    kind: "postgres",
    db: pool,
    run,
    get,
    all,
    transaction,
    close,
  };
}

function openDatabaseClient(options = {}) {
  const explicitDriver = String(options.driver || "").trim().toLowerCase();
  const databaseUrl = String(options.databaseUrl || process.env.DATABASE_URL || "").trim();
  if (explicitDriver === "postgres") {
    if (!databaseUrl) {
      throw new Error("databaseUrl is required when driver is set to postgres.");
    }
    return createPgClient(databaseUrl);
  }

  if (explicitDriver === "sqlite") {
    if (options.isProduction) {
      throw new Error("SQLite is not allowed in production.");
    }
    const sqlitePathFromDriver = String(options.sqlitePath || "").trim();
    if (!sqlitePathFromDriver) {
      throw new Error("sqlitePath is required when driver is set to sqlite.");
    }
    return createSqliteClient(sqlitePathFromDriver);
  }

  if (databaseUrl) {
    return createPgClient(databaseUrl);
  }

  const sqlitePath = String(options.sqlitePath || "").trim();
  if (!sqlitePath) {
    throw new Error("sqlitePath is required when DATABASE_URL is not set.");
  }
  return createSqliteClient(sqlitePath);
}

module.exports = {
  openDatabaseClient,
};
